spring:
  profiles:
    active: ${name:local}
server:
  port: 8091
  base-url: https://softeer.store:8080
  parts-share-url: https://watermelon-clap.web.app/share
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,caches