spring:
  profiles:
    active: ${name:local}
server:
  port: 8091
#  base-url: http://43.202.54.29:8080
  parts-share-url: http://localhost:5173/share
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,caches