spring:
  profiles:
    active: ${name:local}
server:
  port: 8080
#  tomcat:
#    accept-count: 1
#    max-connections: 250
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,caches
logging:
  level:
    org.springframework.transaction.interceptor: TRACE
    org.springframework.orm.jpa.JpaTransactionManager: TRACE
    org.springframework.orm.jpa.EntityManagerFactoryUtils: TRACE
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE