name: Order-Deploy

on:
  pull_request:
    branches:
      - deploy
    types:
      - closed
    paths:
      - "lottery/**"
      - "order/**"
      - "common/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      # 스니펫을 불러온다.
      - name: Download multiple files as an artifact
        uses: actions/download-artifact@v3
        with:
          name: order-snippets
          path: order/build/generated-snippets/

      - name: Download multiple files as an artifact
        uses: actions/download-artifact@v3
        with:
          name: lottery-snippets
          path: lottery/build/generated-snippets/

      - name: Verify files downloaded
        run: |
          echo "Download Files"
          ls -la order/build/generated-snippets/
          ls -la lottery/build/generated-snippets/

      - name: Generate Swagger Document
        run: |
          ./gradlew mergeApiSpecs
          ./gradlew openapi3
          ./gradlew customGenerateSwaggerUI
          ls

      # 스웨거를 업로드한다.
      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-northeast-2'  # 리전 정보
          SOURCE_DIR: 'swagger-ui-watermelon'  # 업로드할 파일들이 위치한 로컬 디렉토리
          AWS_S3_BUCKET: 'watermelon-s3-bucket'  # S3 버킷 이름